# -*- coding: utf-8 -*-
"""Dictionary methods & Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Komal-941/Core_Pythonn/blob/main/Dictionary%20methods%20%26%20Operations.ipynb

# dict methods
"""

marks = {"history":45,"Hindi":56 ,"English" :56 }  #in case of duplicate values; no issue will be created
marks

"""**1.dict.items()** return the key: value pair present in dict in format of list of tuple"""

marks = {"history":45,"Hindi":56 ,"English" :56 }

marks.items()

"""**2.dict.keys()**
- return the keys in dict
"""

marks.keys()

"""**3.dict.values()**
- return the values in dict
"""

marks.values()

"""# Dict Operation

**adding single or Multiple value**
"""

marks = {"history":45,"Hindi":56 }
marks.update({"eng":78})
marks

marks.update({23:67, "Ks":34.87 , 67.9:True})
marks

"""**deleting the values**
- syn : del[dictkey]
"""

marks = {'history': 45, 'Hindi': 56, 'eng': 78, 23: 67, 'Ks': 34.87, 67.9: True}
del marks["Hindi"]
print(marks)

"""**dict.clear**"""

marks = {'history': 45, 'Hindi': 56, 'eng': 78}
marks.clear()
marks

"""**dict.copy**"""

marks = {'history': 45, 'Hindi': 56, 'eng': 78}
new_marks = marks.copy()

new_marks.update({"chem": 90})
print(marks)
new_marks

"""**replacing Values**"""

marks = {'history': 45, 'Hindi': 56, 'eng': 78}
marks['Hindi'] = 76
marks

"""**replacing keys**"""

d ={"Ks":43,"Sk":90,"hs":65}
d.pop("Sk")

