# -*- coding: utf-8 -*-
"""Indexing .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Komal-941/Core_Pythonn/blob/main/Indexing%20.ipynb

# Indexing
- To extract sngle character from string
- Indexing start with zero

### Syntax : Variable name[index number]
"""

s = ("welcome to naresh IT")

len(s)                #this gives the count of negavtive index number

print(len(s) -1)       # This give the count of positive index number

s[3]

s[-17]

s[-22]           # will show the error as -22 value dowwn't exist

s[1.5]             #it gives an output only for int

s[0]           #will show the first character

s[-1]           #will show the last character other syntax s[len(s)-1]

s[len(s)-1]