# -*- coding: utf-8 -*-
"""List Methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Komal-941/Core_Pythonn/blob/main/List%20Methods.ipynb

# List Methods

**1.list.append()**
- Only 1 item can add and at the end only
"""

t= [12.4, 56, "science", 45, True ]

t.append(False)
print(t)

t1= [12.4, 56, "science", 45, True ]          # we have added a list as a single item in main list

t1.append(["Ks",9,4,2001,23.5])
print(t1)

"""**2.list.extend()**
- can add multiple item and it will add each item at the end
- whatever item need to add , make a list of them and apply extend()
"""

r= ["Shelar",10,34.7,False ]

r.extend([True, 89,"Komal", 23.4, 87.6])
print(r)

type(r)

e = [ 10 , 3.5, 76]

e.extend(["Da", 98,23.8])
print(e)

"""**3.list.insert()**
- will add the item at specific position as we want
"""

k= ["Komal", "Shelar"]
print(k)

k.insert(1, "Sopan")
print(k)

k.insert(3, 7721062452)
print(k)

"""**4.list.remove()**
- Remove the item (only one at a time)
- if value is repeated it will remove the first value
"""

j=[2,4,6,7,6,4,2]

j.remove(4)
print(j)

"""**To remove all repetative values**"""

f= [10,20,20,10,20,101,30,70,10,10,20,]
print(f)

f.remove(10)                            #it will remove the first 10 only
print(f)

n= [10,20,20,10,20,101,30,70,10,10,20,]

n=list(set(n))
n.remove(10)                            #it will remove the all 10 values
print(n)

"""**5.list.pop()**
- it will remove the item using index number
- if the index number is not given will take -1 as by default
"""

h=[12.4,56.7,21,"Komal", "Shelar"]

h.pop()                 #by default will remove last value
print(h)

h.pop(3)
print(h)

"""**6.list.clear**
- will empty the list (only values inside the list are deleted)
"""

l=[1,2,3,4]
l.clear()
print(l)

"""**7.list.del()**
- it will delete the whole thing
"""

r= [3.4,5,True]

del r

"""**8.list.count**
- will count the repeatative values
"""

o=[1,2,3,4,1,3,2,6,4,2,7,1,3,1,3,2,1,1]
o.count(1)

"""**9.list.reverse()**
- will reverse all the items in list
"""

a = [12,20,[23,32],"komal"]

a.reverse()
print(a)

"""**10.list.sort**
- will sort the list in ascending or descending order
- by default it will take ascending
"""

k = [1,7,3,6.7,9,2.3]
k.sort()
print(k)                #ascending order --> min to max

k = [1,7,3,6.7,9,2.3]
k.sort(reverse= True)                # descending order --> max to min
print(k)

"""**11.list.copy**
- Deep Copy -  values and id are same
- Shallow Copy - values are same but ids are diffrent as it will create another object
"""

#deep copy
a=[1,2,3,4]
b=a
b.append(5)
print(a)
print(b)

#shallow copy
a=[1,2,3,4]
b=a.copy()
b.append(5)
print(a)
print(b)

