# -*- coding: utf-8 -*-
"""Operators & Types .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Komal-941/Core_Pythonn/blob/main/Operators%20%26%20Types%20.ipynb

# operator
- it is keyword or special symbol that perfoms operation on values & variables

**Types of Operators**
- Arithmetic Operator
- Assignment Operator
- Comparison(Relational) Operator
- Logical Operator
- Membership Operator
- Identity Operator

**1. Arithmetic Operator**
- use to perform mathematical operation
- +, _ , * , / , %(moduluo) , //(floor divison) , **(exponents)
"""

7+5

4-5

3*9

6/2   # div : always gives output in float

9//4 #floor div: gives the quotient value ; here  9 is divident and 4 is divisor ; 2 is quotient and  1 is remaining value

9%4  # Modulo : it gives the remainder

2**2   #exponent : to calculate the power like square , cube, forth root

(5*8)    #paranthesis

"""**in the arithmetic operation, the boolean values automatically coverts to int i.e, True = 1 , False = 0**"""

True + True

False + False

"""**2.Assignment Operator**
- used to assign the value to variables
- = , += , -= , /= , %= , //= , **=
- RHS will execute first and the LHS
"""

y= 5
y= y+4
print(y)

y=5
y+=4
print(y)

y=10
y*=4
print(y)

y=10
y/=4
print(y)

y=6
y**=2
print(y)

"""**3.Comparison(Relational) Operator**
- It gives o/p as bolean only (True or False)
- Used to compare two values only not the data
- ==(equal to), !=(not equal to), >, < , <= , >=
"""

5==5

5==3

5!=5   #as they r same values it shows the false coz != this for not equal to

8>9

8.9<9.0

19>=10

"""**4.Logical Oprator**
- will gives o/p as boolean only.
- and, or,not
  
    **Logical operator Precedence**
  - Logical NOT
  - Logical AND
  - Logical OR
"""

5<3 and 2<3                   # all conditions needs to be true in the and opertor

5<4 or 2<3                    #min one condition should be true

# T or F and T         ( here as per operators precedence will fisrt focus on comparison operator)
# T or F               (as per Logical Operator prece it fisrt focus on AND ope. and then Or Ope.)
# T                    ( as in Or oper. min one cond is true)
4>3 or  2>5 and 5<6

# b = false or not True and true
# b = false or False and True
# b = false or False
#b = False
b = False or not (5>2) and True
print(b)

"""**5.Identity Operator**
- to check if two values or variables are indicating the same object
- Return the o/p as boolean
- is, is not
"""

a= 3
b=3
a is b

print (id(a))

print (id(b))      # both id are matched

x= 6
y=8
x is not y

print (id(x))

print (id(y))  # ids are differnt

"""**6.Membership Operators**
- used to check whether a value or variable are in sequence(str,list,tuple,set & dict)
- returns o/p as boolean
- in , not in
"""

a = "venkatesh"
"tes" in a

a = "venkatesh"
"ter" in a