# -*- coding: utf-8 -*-
"""Set .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Komal-941/Core_Pythonn/blob/main/Set%20.ipynb

# set{}

**Empty set**
"""

l = set()
print(l)

"""**unorder set**"""

s ={23,65,79,2.8,3.4}  # it may or may not be print in a order
print(s)

"""**mutable objects not accepted**"""

s ={1,4.5, False, "Komal" , (1,4,6)}             # all the values in set are immutable
print(s)

"""**will not count duplicates**"""

s ={1,2,3,4,3,2,1,5,2,3,5,7}             #automatically duplicates will remove
print(s)

len(s)

