# -*- coding: utf-8 -*-
"""Slicing .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Komal-941/Core_Pythonn/blob/main/Slicing%20.ipynb

# slicing
- to extract the multiple character values from string
- to extract the multiple values from advanced data type
- Index error is imposible in this case

#### syntax : Variabel_name[start index number (included):ending index number(excluded)]

#### syntax : Variabel_name[starting index number (included):ending index number(excluded): Step]
"""

t = ("welcome")

print(len(t)-1)           #to know the trailing index number

t[0:4]

t[1:-3:1]

t[-2:0:1]     # given step direct is in posstive dire --> so the there is no value for RHS it shows string as empty

t[1:8:1]      # as 8 is an out of range number it will show all the characters avalaible after the starting index number

t[-2:-4:-1]

t[5:-6:-1]  #its in negavtive direction

t[2:4:-1]

l=[10,20,[30,40,[50,60,"hello"]],80]
l[2][2][1]

l[2][2][-1]

