# -*- coding: utf-8 -*-
"""Tuples .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Komal-941/Core_Pythonn/blob/main/Tuples%20.ipynb

# Tuple()

**Empty Tuple**
"""

l=()
print(l)
type(l)

"""**Tuple Indexing**"""

tup= ("siva",25,25.0, True, [50,(10,100)])
print(type(tup))

print(type(tup[-1]))                  # Tup[-1] is [50,(10,100)]

tup[-1]

"""**Tuple Slicing**"""

tup= ("siva",25,25.0, True, [50,(10,100)])
tup[0:4]

tup[::-1]                       # reverse dirn

tup[1:3]

