# -*- coding: utf-8 -*-
"""While Loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Komal-941/Core_Pythonn/blob/main/While%20Loop.ipynb

# While Loop
"""

x=1                #in while          #again it will check for while since it is a LOOP #again it will check for while since it is a
while x<3:         #1<3 (True codn)   #2<3 (True codn)                                  #3<3(False Condn)
    print("Ks")    #ks printed        #ks printed                                       #so the condn will fail and will stop execution
    x = x+1        #x = 1+1 =2        #x = 2+1 =3
                   #Ks will be printed for twice

#nested while ---> while in a while
#we wanna  print two values for 5 times
i=1
j = 1
while i<=5:
    print("telusko")
    i= i+1
    while j <=5:
        print("rocks")
        j =  j+1         # first it will enter to a 2nd while condn(inner loop) complete the loop condn and then again will go first while condn

i=1

while i<=5:
    print("telusko", end=" ")
    j = 1
    while j <=5:
        print("rocks",end=" ")
        j =  j+1
    i= i+1
    print()

print("Ks")
print("Ks")
print("Ks")
print("Ks")
print("Ks")
print("Ks")
print("Ks")

#instead of writing a same line for multiple times and gets printed we cando a looop

x=1
while x<=7:
    print("Ks")
    x=x+1            #the another method to print same line for many times

#in this we have implimented 2 condns
#firstly 1<5 condn satisfies so the DA will print---->DA
# now x = 2
#2==3 condn fails so it will again go for while block
#2<5 condn satisfies so the DA will print ----->DA
#now x = 3
#3==3 condn satisfies and the break the condn


x = 1

while x<5:
    print("DA")
    x= x+1
    if x==3:
        break

"""**While True - it is infinite loop . thi will stop using break only**"""

x=1
while True :
    print(x,"Komal")
    if x==6:
        break
    x=x+1

"""Q. check for the student named a mahesh"""

while True:                   # it will ask for input until the if condn satisfies
    name = input("Enter the name :")
    if name =="Mahesh" or name=="mahesh":
        break

x=1                    #DA -->x=1 ;x<=10 and x<=-20
while x<=10:           #DA -->x=-4 ;x<=10 and x<=-20
    print("DA")        #DA -->x=-9 ;x<=10 and x<=-20
    x= x-5             #DA -->x=-14 ;x<=10 and x<=-20
    if x<=-20:         #DA -->x=-19 ;x<=10 and x<=-20
        break

x = 1

while x<7:
    print(x,"DA")
    if x==6:
        break
    x= x+1

"""Q. Ask the user to put a 5 numbers and do sum"""

s =0
x=1
while x<=5:
    n=eval(input("Enter the number:"))
    s=s+n
    x=x+1

print(s)

"""**Q.Ask use to enter multiple values and do sum**"""

print("Enter all the numbers wanted & once done with all enter a #")
s=0                                   #if we didn't put a s=0 or assign a value to s it will throw a error
while True:                           #as asking for multiple values , it is an infinite loop
    n= input("Enter the numbers:")
    if n=="#":                        #after assign a # to n it cant convert it to any other data type so the error raise
        break
    s=s+eval(n)
print("Sum of all values",s)

"""## **while else**

- if break executed , else will not execute
- if break not  executed , else will execute
-
"""

x = 1
while x<=5:
    print("DA")
    x= x+1           #here while condition(while x<=5) fails as x=6; so the break is ot executed
    if x==13:        # as written above break is not executed ; elese will execute
        break
else:
    print("python")

